/**:
  ros__parameters:
    filter1:
      name: shadows
      type: laser_filters/ScanShadowsFilter
      params:
        min_angle: 5.
        max_angle: 178.
        neighbors: 20
        window: 1
    # filter2:
    #   name: dark_shadows
    #   type: laser_filters/LaserScanIntensityFilter
    #   params:
    #     lower_threshold: 100.
    #     upper_threshold: 10000.
    #     disp_histogram: 0

